AWSTemplateFormatVersion: "2010-09-09"
Description: IaC demo for COBL-004

Resources:

  SimpleBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "cobl004-simple-bucket-asha11"

  SimpleLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  SimpleLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.9
      Handler: index.handler
      Role: !GetAtt SimpleLambdaRole.Arn
      Timeout: 10
      Code:
        ZipFile: |
          def handler(event, context):
              print("Triggered:", event)
              return "OK"

Outputs:
  BucketName:
    Value: !Ref SimpleBucket
  LambdaName:
    Value: !Ref SimpleLambdaFunction
